### ISSUE TITLE
awx_inventory_source doesn't allow empty credentials ID

### ISSUE THREAD

**Issue by fciava** [denouche/terraform-provider-awx#19] opened 2022-09-13 15:35 UTC
Hi,
AWX API permits to create an inventory source without specifying the credentials: if the credential ID is not passed it defaults to "None" instead of the expected integer.
However the current code casts the input to int and so passes "0" to the API instead of "None" returning this error:

 resource "awx_inventory_source" "dynamic_inventory_source" {
│ 
│ Unable to create Inventory Source got Errors:
│ - credential: [Credential 0 does not exist]

This is particular problematic because it forces to create and use an AWS user instead of relying on the assume role inside ec2_plugin.

I've tried working it around inside the provider resource code but I'm not that much into Golang.

**Comment by fciava** [comment] 2022-09-14 09:36
Changing the type inside the resource to "TypeString" (and the casts as well) I get the following error:

resource "awx_inventory_source" "dynamic_inventory_source" {
│ 
│ Unable to create Inventory Source got Errors:
│ - credential: [A valid integer is required.]

So I think there's work to do inside the https://github.com/denouche/goawx.git repository as well @denouche

**Comment by denouche** [comment] 2022-11-14 14:21
Hello @fciava , I just pushed a PR trying to fix this bug.
Can you test if this branch of the provider resolve the issue on your side?

**Comment by Tioborto** [comment] 2022-11-14 14:24
Hello @fciava 
You can try to use by using this example : 
```
terraform {
  required_providers {
    awx = {
      source  = "github.com/denouche/awx"
      version = "fix-inventory-source-no-credential"
    }
  }
}

**Comment by fciava** [comment] 2022-11-15 08:46
Hello @denouche and @Tioborto,
thank you very much for your help.

I can confirm you that's working with both no credentials, with credential id set to 0 and to "0".

e.g.:
resource "awx_inventory_source" "dynamic_inventory_source" {
  name              = "dynamic_inventory_source"
  inventory_id      = awx_inventory.dynamic_inventory.id
  credential_id     = "0"
  overwrite         = true
  source            = "scm"
  source_project_id = awx_project.dynamic_inventory_project.id
  source_path       = "inventories/aws/all_running_hosts.aws_ec2.yml"
}

**Comment by spacex** [comment] 2022-11-21 23:28
I am seeing the same problem with `source_project_id`, not allowing a 0 value when not necessary, such as for ec2 sources.

**Comment by spacex** [comment] 2022-12-03 15:25
I created a new pull request to the same branch with the fix for source_project_id.

**Comment by cwilloughby-bw** [comment] 2023-04-28 18:52
Hey @denouche! I've tested the PR locally as well, and confirmed it worked. Is there anything pending that PR being merged? I'd love to be able to point at the "official" release rather than a local build.

**Comment by fernandoeickhoff-lk** [comment] 2023-11-13 20:20
Hello @denouche I've another issue https://github.com/denouche/terraform-provider-awx/issues/33 opened with this same `source_project_id` issue. Is it possible to merge the PR https://github.com/denouche/terraform-provider-awx/pull/29/? Looks like it solves the issue

**Closed** 2023-11-23 20:51 UTC
