### ISSUE TITLE
Question about source_project_id

### ISSUE THREAD

**Issue by roondar** [denouche/terraform-provider-awx#17] opened 2022-07-26 13:09 UTC
Hello @denouche, 

Do you know why "source_project_id" has been commented ? 
Because it's require when you want to use a SCM inventory https://docs.ansible.com/ansible-tower/latest/html/administration/scm-inv-source.html#update-on-project-update
https://github.com/denouche/terraform-provider-awx/blob/35bfd380056745c239b02d9146e754873ae597b7/awx/resource_inventory_source.go#L139

Furthermore, this parameter still exists in the API https://github.com/ansible/awx/blob/devel/awx/api/serializers.py#L2098

Thanks

**Comment by roondar** [comment] 2022-07-26 13:12
![image](https://user-images.githubusercontent.com/634279/181014227-61c4208d-276c-4093-bb3e-aae367c83898.png)

**Comment by fciava** [comment] 2022-09-02 00:31
+1

**Comment by fciava** [comment] 2022-09-02 06:49
By just adding this to the schema and uncommenting the lines inside the function I can confirm it works just fine. I compiled the provider locally.

			"source_project_id": {
				Type:     schema.TypeInt,
				Optional: true,
			},
			"source_path": {
				Type:     schema.TypeString,
				Optional: true,
			},

**Comment by roondar** [comment] 2022-09-02 07:19
I'm working on it, I'll propose you a PR soon.🙂

**Comment by fciava** [comment] 2022-09-08 06:42
Hello @roondar, any news regarding this topic? Otherwise I can try to make a PR during the WE. Thanks

**Comment by roondar** [comment] 2022-09-08 09:14
Yeah sorry, I'm a bit busy at the moment, to be honest I'm working on adding some other features.
So be patient :p

**Comment by fivetran-joliveira** [comment] 2022-09-14 10:32
> By just adding this to the schema and uncommenting the lines inside the function I can confirm it works just fine. I compiled the provider locally.

Hey @fciava @roondar 
Would it be possible or you to send a separate PR only fixing the inventory source `source_project_id` support as you already have it working?

**Comment by Chavo11** [comment] 2022-09-16 14:34
Hi @fivetran-joliveira @roondar, I've just created the PR with the fixes. Hopefully it will be merged soon.

https://github.com/denouche/terraform-provider-awx/pull/20

**Comment by roondar** [comment] 2022-09-16 15:43
As requested, my PR : 
- https://github.com/denouche/terraform-provider-awx/pull/21
- https://github.com/denouche/goawx/pull/13

**Comment by roondar** [comment] 2022-10-03 07:16
Any update @denouche ?

**Comment by denouche** [comment] 2022-11-14 14:07
Hello, I close this issue since the original question has been resolved by #20

**Closed by denouche** 2022-11-14 14:07 UTC
